#!/bin/bash
# Use this for your user data (script from top to bottom)
# install httpd (Linux 2 version)
yum update -y
yum install git.x86_64 -y
git clone https://github.com/ihsin/portfolio-rahul.git
cd portfolio-rahul
pip3 install -r requirements.txt
python3 app.py