version: "2"
services:
  app:
    container_name: portfolio-web
    build: .
    links:
      - db
    depends_on: 
      - db
    ports:
      - "8080:8080"
  db:
    container_name: portfolio-db
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feedback
    volumes:
      - ./db:/docker-entrypoint-initdb.d/